<<<<<<< HEAD
societe_front:
    resource: "@SocieteFrontBundle/Resources/config/routing.yml"
    prefix:   /

societe_back:
    resource: "@SocieteMainBundle/Resources/config/routing.yml"
    prefix:   /admin

=======
>>>>>>> parent of f73677a... security (login,...)
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
