Societe\BackBundle\Entity\Societe:
    type: entity
    table: societe
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 250
            fixed: false
        ville:
            type: string
            nullable: false
            length: 250
            fixed: false
        codePostal:
            type: string
            nullable: false
            length: 250
            fixed: false
            column: code_postal
        telephone:
            type: string
            nullable: false
            length: 15
            fixed: false
        logo:
            type: string
            nullable: false
            length: 250
            fixed: false
    lifecycleCallbacks: {  }
